# Generated by Django 4.1.4 on 2023-01-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XAxis', models.CharField(max_length=25)),
                ('YAxis', models.CharField(max_length=25)),
            ],
        ),
    ]
